apiVersion: apps/v1
kind: Deployment
metadata:
  name: application
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
      annotations:
        'consul.hashicorp.com/connect-inject': 'true'
        'consul.hashicorp.com/connect-service': 'auth'
    spec:
      containers:
      - name: auth
        image: oyas/web-app-auth
        ports:
        - containerPort: 50054
        env:
        - name: APP_REDIS_URL
          value: "redis-auth:6379"
        - name: APP_JAEGER_URL
          value: "http://localhost:14268"
        - name: SIGNING_KEY_PATH
          value: "/app/keys/app.rsa"
        volumeMounts:
        - name: rsa-key
          mountPath: "/app/keys"
          readOnly: true
      - name: otel-collector
        image: otel/opentelemetry-collector-contrib
        args: ["--config=/etc/otel-collector-config.yaml"]
        ports:
        - containerPort: 14268
        volumeMounts:
        - name: otel-collector-config
          mountPath: "/etc/otel-collector-config.yaml"
          readOnly: true
          subPath: otel-collector-config.yaml
      volumes:
      - name: rsa-key
        secret:
          secretName: secret-rsa-key
      - name: otel-collector-config
        configMap:
          name: otel-collector-config
          items:
            - key: otel-collector-config.yaml
              path: otel-collector-config.yaml
