apiVersion: apps/v1
kind: Deployment
metadata:
  name: application
spec:
  replicas: 1
  selector:
    matchLabels:
      app: articles
  template:
    metadata:
      labels:
        app: articles
      annotations:
        'consul.hashicorp.com/connect-inject': 'true'
        'consul.hashicorp.com/connect-service': 'articles'
    spec:
      containers:
      - name: articles
        image: oyas/web-app-articles
        ports:
        - containerPort: 50052
        env:
        - name: APP_REDIS_URL
          value: "redis-articles:6379"
        - name: APP_JAEGER_URL
          value: "http://localhost:14268"
      - name: otel-collector
        image: otel/opentelemetry-collector-contrib
        args: ["--config=/etc/otel-collector-config.yaml"]
        ports:
        - containerPort: 14268
        volumeMounts:
        - name: otel-collector-config
          mountPath: "/etc/otel-collector-config.yaml"
          readOnly: true
          subPath: otel-collector-config.yaml
      volumes:
      - name: otel-collector-config
        configMap:
          name: otel-collector-config
          items:
            - key: otel-collector-config.yaml
              path: otel-collector-config.yaml
