apiVersion: apps/v1
kind: Deployment
metadata:
  name: application
spec:
  replicas: 1
  selector:
    matchLabels:
      app: articles
  template:
    metadata:
      labels:
        app: articles
      annotations:
        'consul.hashicorp.com/connect-inject': 'true'
        'consul.hashicorp.com/connect-service': 'articles'
    spec:
      containers:
      - name: articles
        image: oyas/web-app-articles
        ports:
        - containerPort: 50052
        env:
        - name: APP_REDIS_URL
          value: "redis-articles:6379"
        - name: HOST_IP
          valueFrom:
            fieldRef:
              fieldPath: status.hostIP
        - name: APP_JAEGER_URL
          value: "http://$(HOST_IP):14268"
