apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  finalizers:
  - resources-finalizer.argocd.argoproj.io
  name: consul
  namespace: argocd
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: consul
  project: default
  source:
    repoURL: https://github.com/hashicorp/consul-helm
    path: .
    targetRevision: v0.31.1
    helm:
      version: v3
      values: |
        global:
          name: "consul"
          datacenter: staging-gke
        server:
          replicas: 1
        client:
          enabled: true
          grpc: true
        connectInject:
          enabled: true
        controller:
          enabled: true
  syncPolicy:
    automated:
      prune: true
      selfHeal: false
    syncOptions:
    - CreateNamespace=true
