apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-internal-conf
data:
  nginx.conf: |
    user nginx;
    worker_processes 1;

    events {
      worker_connections  1024;
    }

    stream {
      server {
        listen     20000;
        proxy_pass argocd-server.argocd:443;
      }
      server {
        listen     20001;
        proxy_pass consul-server.consul:8500;
      }
      server {
        listen     20002;
        proxy_pass grafana.grafana:80;
      }
      server {
        listen     20003;
        proxy_pass prometheus-alertmanager.prometheus:80;
      }
      server {
        listen     20004;
        proxy_pass prometheus-server.prometheus:80;
      }
    }

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-internal
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-internal
  template:
    metadata:
      labels:
        app: nginx-internal
    spec:
      containers:
      - name: nginx
        image: nginx
        ports:
        - name: argocd
          containerPort: 20000
        - name: consul
          containerPort: 20001
        - name: grafana
          containerPort: 20002
        - name: alertmanager
          containerPort: 20003
        - name: prometheus
          containerPort: 20004
        volumeMounts:
        - name: nginx-conf
          mountPath: /etc/nginx/nginx.conf
          readOnly: true
          subPath: nginx.conf
      volumes:
      - name: nginx-conf
        configMap:
          name: nginx-internal-conf
          items:
            - key: nginx.conf
              path: nginx.conf
