apiVersion: v1
kind: ConfigMap
metadata:
  name: otel-collector-config
data:
  otel-collector-config.yaml: |
    receivers:
      otlp:
        protocols:
          grpc:
      jaeger:
        protocols:
          thrift_http:
    exporters:
      logging:
      jaeger:
        endpoint: "jaeger-collector.jaeger:14250"
      otlp/tempo:
        endpoint: "tempo.tempo:4317"
    processors:
      batch:
    service:
      extensions: []
      pipelines:
        traces:
          receivers: [otlp, jaeger]
          processors: [batch]
          exporters: [logging, jaeger, otlp/tempo]
