apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app
  namespace: argocd
spec:
  destination:
    namespace: app-staging-frontend
  source:
    path: apps/frontend/overlays/staging
