apiVersion: apps/v1
kind: Deployment
metadata:
  name: application
spec:
  replicas: 1
  selector:
    matchLabels:
      app: application
  template:
    metadata:
      labels:
        app: application
    spec:
      containers:
      - name: application
        image: oyas/web-app-bff
        ports:
        - containerPort: 4000
        env:
        - name: API_URL_ARTICLES
          value: "http://application.app-dev-articles.svc.cluster.local:50052"
