apiVersion: apps/v1
kind: Deployment
metadata:
  name: application
spec:
  replicas: 1
  selector:
    matchLabels:
      app: application
  template:
    metadata:
      labels:
        app: application
      annotations:
        'consul.hashicorp.com/connect-inject': 'true'
        'consul.hashicorp.com/connect-service': 'bff'
        'consul.hashicorp.com/connect-service-upstreams': 'articles:50000,auth:50054'
    spec:
      containers:
      - name: application
        image: oyas/web-app-bff
        ports:
        - containerPort: 4000
        env:
        - name: API_URL_ARTICLES
          value: "localhost:50000"
        - name: API_URL_AUTH
          value: "localhost:50054"
        - name: APP_JAEGER_URL
          value: "http://localhost:14268"
      - name: otel-collector
        image: otel/opentelemetry-collector-contrib
        args: ["--config=/etc/otel-collector-config.yaml"]
        ports:
        - containerPort: 14268
        volumeMounts:
        - name: otel-collector-config
          mountPath: "/etc/otel-collector-config.yaml"
          readOnly: true
          subPath: otel-collector-config.yaml
      volumes:
      - name: otel-collector-config
        configMap:
          name: otel-collector-config
          items:
            - key: otel-collector-config.yaml
              path: otel-collector-config.yaml
