apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  finalizers:
  - resources-finalizer.argocd.argoproj.io
  name: grafana
  namespace: argocd
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: grafana
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: false
    syncOptions:
    - CreateNamespace=true
  source:
    repoURL: https://github.com/grafana/helm-charts
    path: charts/grafana
    targetRevision: main
    helm:
      version: v3
      values: |
        # adminPassword: admin
        grafana.ini:
          auth.anonymous:
            enabled: true
            org_name: Main Org.
            org_role: Admin
        datasources:
          datasources.yaml:
            apiVersion: 1
            datasources:
            - name: Prometheus
              type: prometheus
              url: http://prometheus-server.prometheus
              isDefault: true
            - name: Tempo
              type: tempo
              url: http://tempo.tempo:3100
              uid: tempo
            - name: Loki
              type: loki
              url: http://loki.loki:3100
              jsonData:
                derivedFields:
                - datasourceUid: tempo
                  matcherRegex: (?:traceID|trace_id)=(\w+)
                  name: TraceID
                  url: $${__value.raw}
                - datasourceUid: tempo
                  matcherRegex: \"?traceparent\"?\s*[:=]\s*\"?[0-9a-f]{2}-([0-9a-f]{32})-[0-9a-f]{16}-[0-9a-f]{2}\"?
                  name: trace_id_from_traceparent
                  url: $${__value.raw}
        dashboardProviders:
          dashboardproviders.yaml:
            apiVersion: 1
            providers:
            - name: 'default'
              orgId: 1
              folder: ''
              type: file
              disableDeletion: false
              editable: true
              options:
                path: /var/lib/grafana/dashboards/default
        dashboards:
          default:
            Logs:
              json: |
                {
                  "schemaVersion": 30,
                  "title": "Logs-imported",
                  "uid": "Logs-imported",
                  "editable": true,
                  "panels": [
                    {
                      "datasource": "Loki",
                      "gridPos": {
                        "h": 15,
                        "w": 24,
                        "x": 0,
                        "y": 0
                      },
                      "id": 0,
                      "options": {
                        "dedupStrategy": "none",
                        "enableLogDetails": true,
                        "prettifyLogMessage": true,
                        "showCommonLabels": false,
                        "showLabels": false,
                        "showTime": true,
                        "sortOrder": "Ascending",
                        "wrapLogMessage": true
                      },
                      "targets": [
                        {
                          "expr": "{pod=\"jaeger-collector-7cb855bbdf-sflpm\"}\n| pattern \"<original_log>\"\n| json\n| __error__ != \"JSONParserErr\"\n| line_format `[{{ .caller }}] {{ .msg }} {{- with .error }} ; {{ . }} {{- end }}\n{{ .stacktrace }}`",
                          "refId": "A"
                        },
                        {
                          "expr": "{pod=\"jaeger-collector-7cb855bbdf-sflpm\"}\n| pattern \"<original_log>\"\n| json\n| __error__ = \"JSONParserErr\"",
                          "refId": "B"
                        }
                      ],
                      "title": "jaeger-collector",
                      "type": "logs"
                    },
                    {
                      "datasource": "Loki",
                      "gridPos": {
                        "h": 15,
                        "w": 24,
                        "x": 0,
                        "y": 15
                      },
                      "id": 2,
                      "options": {
                        "dedupStrategy": "none",
                        "enableLogDetails": true,
                        "prettifyLogMessage": true,
                        "showCommonLabels": false,
                        "showLabels": false,
                        "showTime": true,
                        "sortOrder": "Ascending",
                        "wrapLogMessage": true
                      },
                      "targets": [
                        {
                          "expr": "{container=\"auth\",namespace=\"app-dev-auth\"}\n| pattern \"<original_log>\"\n| json\n| __error__ != \"JSONParserErr\"\n| line_format `[{{ .caller }}] {{ .msg }} {{- with .error }} ; {{ . }} {{- end }} {{- with .stacktrace }}\n{{ . }} {{- end }}`",
                          "refId": "A"
                        },
                        {
                          "expr": "{container=\"auth\",namespace=\"app-dev-auth\"}\n| pattern \"<original_log>\"\n| json\n| __error__ = \"JSONParserErr\"",
                          "refId": "B"
                        }
                      ],
                      "title": "Auth",
                      "type": "logs"
                    }
                  ]
                }
