apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  finalizers:
  - resources-finalizer.argocd.argoproj.io
  name: grafana
  namespace: argocd
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: grafana
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: false
    syncOptions:
    - CreateNamespace=true
  source:
    repoURL: https://github.com/grafana/helm-charts
    path: charts/grafana
    targetRevision: main
    helm:
      version: v3
      values: |
        # adminPassword: admin
        grafana.ini:
          auth.anonymous:
            enabled: true
            org_name: Main Org.
            org_role: Admin
        datasources:
          datasources.yaml:
            apiVersion: 1
            datasources:
            - name: Prometheus
              type: prometheus
              url: http://prometheus-server.prometheus
              isDefault: true
            - name: Tempo
              type: tempo
              url: http://tempo.tempo:3100
              uid: tempo
            - name: Loki
              type: loki
              url: http://loki.loki:3100
              # jsonData:
              #   derivedFields:
              #   - datasourceUid: tempo
              #     matcherRegex: (?:traceID|trace_id)=(\w+)
              #     name: TraceID
              #     url: $${__value.raw}
              #   - datasourceUid: tempo
              #     matcherRegex: \"?traceparent\"?\s*[:=]\s*\"?[0-9a-f]{2}-([0-9a-f]{32})-[0-9a-f]{16}-[0-9a-f]{2}\"?
              #     name: trace_id_from_traceparent
              #     url: $${__value.raw}
