apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  finalizers:
  - resources-finalizer.argocd.argoproj.io
  name: prometheus-operator
  namespace: argocd
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: prometheus-operator
  project: default
  source:
    repoURL: https://github.com/prometheus-operator/prometheus-operator
    path: .
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: false
    syncOptions:
    - CreateNamespace=true
