apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  finalizers:
  - resources-finalizer.argocd.argoproj.io
  name: tempo
  namespace: argocd
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: tempo
  project: default
  source:
    repoURL: https://github.com/grafana/helm-charts
    path: charts/tempo-distributed
    targetRevision: main
    helm:
      version: v3
  syncPolicy:
    automated:
      prune: true
      selfHeal: false
    syncOptions:
    - CreateNamespace=true
