apiVersion: apps/v1
kind: Deployment
metadata:
  name: wait-for-consul
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wait-for-consul
  template:
    metadata:
      labels:
        app: wait-for-consul
    spec:
      containers:
      - name: wait-for-consul-finish
        image: busybox
        command: ['sh', '-c', 'echo Consul is running! && while :; do sleep 3600; done']
      initContainers:
      - name: wait-for-consul
        image: busybox
        command: [ "sh", "-c", "until wget --spider --timeout 60 -t 1 consul-server.consul:8500 ; do echo waiting for consul; sleep 2 ; done" ]
