apiVersion: apps/v1
kind: Deployment
metadata:
  name: application
spec:
  replicas: 1
  selector:
    matchLabels:
      app: application
  template:
    metadata:
      labels:
        app: application
    spec:
      containers:
      - name: application
        image: oyas/web-app-frontend
        ports:
        - containerPort: 8000
        env:
        - name: API_URL_BFF
          value: "http://bff:4000"
        - name: API_URL_BFF_RUNTIME
          value: ""
