apiVersion: v1
kind: Service
metadata:
  name: frontend
spec:
  type: ExternalName
  externalName: application.app-staging-frontend.svc.cluster.local
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
