apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: application
spec:
  rules:
  - http:
      paths:
      - path: /graphql
        pathType: Prefix
        backend:
          service:
            name: nginx-service
            port.name: bff
      - path: /
        pathType: Prefix
        backend:
          service:
            name: nginx-service
            port.name: frontend
