apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-conf
data:
  nginx.conf: |
    user nginx;
    worker_processes 1;

    events {
      worker_connections  1024;
    }

    stream {
      server {
        listen     8080;
        proxy_pass localhost:8081;
      }
      server {
        listen     4000;
        proxy_pass localhost:4001;
      }
    }
