apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  selector:
    app: nginx
  ports:
  - name: frontend
    protocol: TCP
    port: 8080
    targetPort: 8080
  - name: bff
    protocol: TCP
    port: 4000
    targetPort: 4000
